# Question

Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log("Inside the loop", i);
  }
  console.log("Outside the loop");
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer

No, the `console.log('Outside the loop');` will never run because, the `return` after the if statement abandons the loop and the function, meaning anything after that `return` will not be executed. 

# Teacher Feedback
